#!/usr/bin/env bash
# install nginx and overwrite default index
str="server {
	error_page 404 /custom_404.html;
	location = /custom_404.html {
		root /usr/share/nginx/html;
		internal;
	}
}"
sudo apt-get -y install nginx;
sudo systemctl start nginx;
echo "Hello World!" > index.nginx-debian.html;
sudo touch /usr/share/nginx/html/custom_404.html;
sudo chmod 777 /usr/share/nginx/html/custom_404.html;
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html;
echo "$str" >> /etc/nginx/sites-enabled/default;
sudo service nginx restart;
