#!/usr/bin/env bash
# Displays numbers from 1 to 100 with FizzBuzz algorithm

for i in {1..100}
do
	if ! (("$i" % 15))
	then
		echo "FizzBuzz"
	elif ! (("$i" % 3))
	then
		echo "Fizz"
	elif ! (("$i" % 5))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
