#!/usr/bin/env bash
# Display "bad luck", "good luck" in 4th and 8th iteration respectively,
# "Best School" otherwise, 10 times
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( x++ ))
done
