#!/usr/bin/env bash
# Display "bad luck", "good luck" in 4th and 8th iteration respectively,
# "Best School" otherwise, 10 times
x=1
while [ $x -le 20 ]
do
	echo "$x"
	case $x in
		4)
			echo "bad luck from China"
		;;
		9)
			echo "bad luck from Japan"
		;;
		17)
			echo "bad luck from Italy"
		;;
	esac
	(( x++ ))
done
