#!/usr/bin/env bash
# gives info about "school" file

f="./school"
if [ ! -e "$f" ]
then
	echo "school file does not exist"
else
	echo "school file exists"
	if [ -s "$f" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$f" ]
	then
		echo "school is a regular file"
	fi
fi
